language: python

sudo: required

services:
  - docker

python:
  - "2.7"

install:
  - pip install flake8

script:
  - flake8 . --max-line-length=100
  - make build
  - make run
  - sleep 5
  - make test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
			docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
			docker push robcurrie/dtmp;
    fi
